version: '3.7'

services:
  # Database Server
  # Use root/example as user/password credentials
  recordingchewers-db:
    container_name: "recordingchewers-db"
    tty: true
    restart: unless-stopped
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - database-local-data:/var/lib/mysql
    networks:
      - local-db

  # phpMyAdmin Service
  recordingchewers-phpmyadmin:
    container_name: "recordingchewers-phpmyadmin"
    tty: true
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=recordingchewers-db
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    networks:
      - local-db

volumes:
  database-local-data:

networks:
  local-db:
    driver: bridge
